// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCadkav7E9ue7ZWM39hbYZ87wjKyMbmBaI',
    appId: '1:51718800484:web:deb6ae4cff5a50d311cb71',
    messagingSenderId: '51718800484',
    projectId: 'mealmaster-d329b',
    authDomain: 'mealmaster-d329b.firebaseapp.com',
    storageBucket: 'mealmaster-d329b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTrFzDqtpj24miFxSHgwggW63UeuM8GgQ',
    appId: '1:51718800484:android:435193c407df806811cb71',
    messagingSenderId: '51718800484',
    projectId: 'mealmaster-d329b',
    storageBucket: 'mealmaster-d329b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRl_GsQiI2bhCsu8C9GXG7TabfNzzJ-O0',
    appId: '1:51718800484:ios:028bafb73c58cea311cb71',
    messagingSenderId: '51718800484',
    projectId: 'mealmaster-d329b',
    storageBucket: 'mealmaster-d329b.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRl_GsQiI2bhCsu8C9GXG7TabfNzzJ-O0',
    appId: '1:51718800484:ios:028bafb73c58cea311cb71',
    messagingSenderId: '51718800484',
    projectId: 'mealmaster-d329b',
    storageBucket: 'mealmaster-d329b.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCadkav7E9ue7ZWM39hbYZ87wjKyMbmBaI',
    appId: '1:51718800484:web:60ad319fcd695a4c11cb71',
    messagingSenderId: '51718800484',
    projectId: 'mealmaster-d329b',
    authDomain: 'mealmaster-d329b.firebaseapp.com',
    storageBucket: 'mealmaster-d329b.firebasestorage.app',
  );
}
